### ISSUE TITLE
Main PCB .brd file missing?

### ISSUE THREAD

**Issue by KeLaiFu** [mkfarrow/Eurorack_Dual-VCS#1]
I was looking for a VCS and found your awesome selection of modules, including this one. However, unlike your other repos, only the panel files seem to be available. Is the main brd file missing?

Looking at the schem, it wouldn't be much to remake it, but obviously I would like to reduce the chances of me making dumb mistakes in kicad.

Thanks for all the great modules!

**Comment by mkfarrow** [comment]
Hey there. I will upload the board file later today. I think I made that VCS in KiCad. It is basically a copy of the Doepfer VCSSent from my iPhoneOn Feb 24, 2023, at 2:40 AM, KeLaiFu ***@***.***> wrote:﻿
I was looking for a VCS and found your awesome selection of modules, including this one. However, unlike your other repos, only the panel files seem to be available. Is the main brd file missing?
Looking at the schem, it wouldn't be much to remake it, but obviously I would like to reduce the chances of me making dumb mistakes in kicad.
Thanks for all the great modules!

**Comment by mkfarrow** [comment]
Hi,

I just pushed a change to the repo that includes the kicad files for the
PCB as well as the gerbers for JLCPCB to manufacture. However there is
something you should know: the design uses the CL1384 Cliff jacks - when I
originally ordered PCBs for this design, I misunderstood the datasheet and
I reversed the pins in the design. My workaround was I just fixed the PCBs
by hand (see photos). But I* did correct the mistake in KiCad* and
re-routed the traces, I just never re-ordered PCBs. So the gerbers in the
repo have been fixed, I just can't say that I have physically verified the
PCBs myself. I fully expect them to work perfectly.

Here are photos that show the hand-wiring hacks I had to do to the original
version (all those jumper wires!!! green, blue, black, as well as the 7 or
8 bare ones running down the right side hahaha):
[image: dualvcs2.jpeg]
[image: dualvcs1.jpeg]
Anyways, like I said, the version in the repository should fix that, but it
might be worth double checking that the pins on the jacks are correctly
routed on the PCB (i.e. the tip is the tip and the ground is the ground).

Let me know if you have any questions or issues. If you live in the USA,
I'd be happy to send you panels/PCBs of any of the modules I have up (just
not the VCS because of the problem described above) if you paid me the
money it costs to mail them in an envelope. I have extra bare PCBs and
panels for most of them. I have a more complete list on my website:
https://mikeyfarrow.com/electronics.php (email michaelkfarrow  [at] gmail.

-Mikey,
